'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Register

    '''<summary>
    '''pnlRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRegister As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''inputFName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputFName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''inputMName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputMName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''inputLName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputLName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''inputNickName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputNickName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''inputEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''vUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vUserName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''inputEmail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputEmail2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CompareEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareEmail As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''inputUserPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputUserPass As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''vUserPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vUserPass As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''inputUserPass2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputUserPass2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ComparePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComparePassword As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''cmdRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRegister As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
End Class
