'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Budgets

    '''<summary>
    '''panelIncomes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelIncomes As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rptIncomes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptIncomes As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btnAddIncome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddIncome As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''panelExpenses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelExpenses As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rptExpenses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptExpenses As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''ctrlExpenses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlExpenses As Global.CodeOne.IncomeExpense

    '''<summary>
    '''ddlCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCategories As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''panelMonthlyExpense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelMonthlyExpense As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rptMonthlyExpenses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptMonthlyExpenses As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lineGraphYay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lineGraphYay As Global.CodeOne.LineGraph
End Class
